Implementacion snyk-yml

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -26,16 +26,25 @@ jobs:
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
+      - name: Change to Project Directory
+        run: cd ProyectoFinal
+
       - name: Snyk Code test
-        run: snyk code test --sarif --all-projects > snyk-code.sarif || echo "Snyk code test failed with exit code $?"
+        run: |
+          cd ProyectoFinal
+          snyk code test --sarif --all-projects > snyk-code.sarif || echo "Snyk code test failed with exit code $?"
 
       - name: Snyk Open Source monitor
-        run: snyk monitor 
+        run: |
+          cd ProyectoFinal
+          snyk monitor 
 
       - name: Snyk IaC test and report
-        run: snyk iac test --report
+        run: |
+          cd ProyectoFinal
+          snyk iac test --report
 
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v3
         with:
-          sarif_file: snyk-code.sarif
+          sarif_file: ProyectoFinal/snyk-code.sarif
